version: "3.9"

services:
  # multirobot_server:
  #   container_name: multirobot_server
  #   build:
  #     context: ./multirobot_server
  #     dockerfile: Dockerfile
  #   image: multirobot_server
  #   networks:
  #     - multirobot_net
  #   restart: unless-stopped

  # multirobot_client:
  #   container_name: multirobot_client
  #   build:
  #     context: ./multirobot_client
  #     dockerfile: Dockerfile
  #   image: multirobot_client
  #   networks:
  #     - multirobot_net
  #   restart: unless-stopped

  multirobot_simulator:
    container_name: multirobot_simulator
    build:
      context: ./multirobot_simulator
      dockerfile: Dockerfile
    image: multirobot_simulator
    networks:
      - multirobot_net
    restart: unless-stopped

networks:
  multirobot_net:
    driver: bridge
